In [1]:
#import dependencies

import pandas as pd
# settings to display all columns
pd.set_option("display.max_columns", None)
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

data_file = "Sql Data/employee_sources.csv"

emp_sources= pd.read_csv(data_file)
emp_sources

,employee_no,position,department,status,manager_name,performance,engagement_score,emp_satisfaction,source,post_education,race_desc,sex,total
0,904013591,Sr. Network Engineer,IT/IS,Active,Peter Monroe,N/A- too early to review,3.27,4,On-campus Recruiting,Bachelors,Asian,Male,"$7,500.00"
1,1308060959,Sr. Network Engineer,IT/IS,Active,Peter Monroe,90-day meets,5.00,3,Employee Referral,Associates,White,Male,$0.00
2,1301052347,Sr. Network Engineer,IT/IS,Active,Peter Monroe,N/A- too early to review,1.06,4,Employee Referral,Bachelors,Asian,Female,$0.00
3,1411071312,Sr. Network Engineer,IT/IS,Active,Peter Monroe,Fully Meets,1.55,5,Vendor Referral,Bachelors,White,Female,$0.00
4,1108028108,Sr. Network Engineer,IT/IS,Active,Peter Monroe,Fully Meets,4.46,5,Employee Referral,Bachelors,White,Male,$0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,1103024456,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,2.04,2,Diversity Job Fair,Bachelors,White,Female,"$10,021.00"
582,1106026572,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,5.00,4,Website Banner Ads,Associates,White,Male,"$7,143.00"
583,1106026572,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,5.00,4,Website Banner Ads,Associates,Black or African American,Male,"$7,143.00"
584,1302053333,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,3.90,5,Internet Search,Bachelors,White,Male,$0.00
585,1103024456,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,2.04,2,Diversity Job Fair,Bachelors,Black or African American,Female,"$10,021.00"

In [2]:
emp_sources.drop_duplicates(subset=['employee_no'], keep='first', inplace=True)
emp_sources

,employee_no,position,department,status,manager_name,performance,engagement_score,emp_satisfaction,source,post_education,race_desc,sex,total
0,904013591,Sr. Network Engineer,IT/IS,Active,Peter Monroe,N/A- too early to review,3.27,4,On-campus Recruiting,Bachelors,Asian,Male,"$7,500.00"
1,1308060959,Sr. Network Engineer,IT/IS,Active,Peter Monroe,90-day meets,5.00,3,Employee Referral,Associates,White,Male,$0.00
2,1301052347,Sr. Network Engineer,IT/IS,Active,Peter Monroe,N/A- too early to review,1.06,4,Employee Referral,Bachelors,Asian,Female,$0.00
3,1411071312,Sr. Network Engineer,IT/IS,Active,Peter Monroe,Fully Meets,1.55,5,Vendor Referral,Bachelors,White,Female,$0.00
4,1108028108,Sr. Network Engineer,IT/IS,Active,Peter Monroe,Fully Meets,4.46,5,Employee Referral,Bachelors,White,Male,$0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,1211050782,Administrative Assistant,Admin Offices,Active,Brandon R. LeBlanc,N/A- too early to review,3.24,3,Pay Per Click - Google,No,White,Female,"$3,509.00"
572,711007713,Administrative Assistant,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,3.80,4,Diversity Job Fair,Associates,Asian,Female,"$10,021.00"
577,1302053333,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,3.90,5,Internet Search,Bachelors,White,Male,$0.00
578,1106026572,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,5.00,4,Website Banner Ads,Associates,White,Male,"$7,143.00"
579,1103024456,Accountant I,Admin Offices,Active,Brandon R. LeBlanc,Fully Meets,2.04,2,Diversity Job Fair,Bachelors,White,Female,"$10,021.00"

In [3]:
emp_sources.drop(['employee_no', 'status', 'manager_name', 'total'], axis=1)

,position,department,performance,engagement_score,emp_satisfaction,source,post_education,race_desc,sex
0,Sr. Network Engineer,IT/IS,N/A- too early to review,3.27,4,On-campus Recruiting,Bachelors,Asian,Male
1,Sr. Network Engineer,IT/IS,90-day meets,5.00,3,Employee Referral,Associates,White,Male
2,Sr. Network Engineer,IT/IS,N/A- too early to review,1.06,4,Employee Referral,Bachelors,Asian,Female
3,Sr. Network Engineer,IT/IS,Fully Meets,1.55,5,Vendor Referral,Bachelors,White,Female
4,Sr. Network Engineer,IT/IS,Fully Meets,4.46,5,Employee Referral,Bachelors,White,Male
...,...,...,...,...,...,...,...,...,...
571,Administrative Assistant,Admin Offices,N/A- too early to review,3.24,3,Pay Per Click - Google,No,White,Female
572,Administrative Assistant,Admin Offices,Fully Meets,3.80,4,Diversity Job Fair,Associates,Asian,Female
577,Accountant I,Admin Offices,Fully Meets,3.90,5,Internet Search,Bachelors,White,Male
578,Accountant I,Admin Offices,Fully Meets,5.00,4,Website Banner Ads,Associates,White,Male
579,Accountant I,Admin Offices,Fully Meets,2.04,2,Diversity Job Fair,Bachelors,White,Female

In [4]:
emp_sources.to_csv("Tableau csv/emp_sources.csv", index=False, header=True)